### ISSUE TITLE
Node version 6.9.2 is unsupported

### ISSUE THREAD

**Issue by faserprodukt** [ExLibrisGroup/primo-explore-devenv#107] opened 2019-07-29 14:23 UTC
Please update the devenv to a version of Node.js that is still supported.

**Comment by atla5** [comment] 2019-07-29 15:53
this is a duplicate of issue #105 and is 90% of the way resolved in pull request #103.  

but yes, please address this.

**Comment by noamamit92** [comment] 2020-07-21 06:05
merge PR

**Closed by noamamit92** 2020-07-21 06:05 UTC
